---
title: "Será que a região contribui na formação do preconceito sexista?"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: cerulean
runtime: shiny
resource_files:
- PROCESSOOPER.R
---

```{r setup, include=FALSE}
setwd("C:\\Users\\LENOVO\\Desktop\\ERICK")

library(flexdashboard)
library(dplyr)
library(tidyr)
library(magrittr)
library(shiny)

base_ipea <- as_tibble(read.csv2("base_ipea.csv", stringsAsFactors = T)) # Lendo a base de dados
```

Análise por Região
=======

Inputs {.sidebar}
----------
```{r}
selectInput("Região", label = "Região onde foi realizada a entrevista:", 
            choices = unique(base_ipea$região.onde.foi.realizada.a.entrevista), selected = "SUDESTE")

```


Row {data-width=650, .tabset}
-----------------------------------------------------------------------

### **Dá pra entender que um homem que cresceu em uma família violenta agrida sua mulher**

```{r}
library(ggplot2)
library(plotly)

renderPlotly({
  grafico1 <- filter(base_ipea, região.onde.foi.realizada.a.entrevista == input$Região) %>%
  ggplot(.,aes(x = dá.para.entender.que.um.homem.que.cresceu.em.uma.família.violenta.agrida.sua.mul, fill = sexo)) +
  geom_bar(position = "dodge") +
  scale_fill_viridis_d(option = "cividis") +
  labs(x = " ", y = "N° de Entrevistados") +
  coord_flip() +
  theme_bw()

ggplotly(grafico1)
})


```

### **Tabela 1 (Resumo com todas regiões)**

```{r}
library(gtsummary)

tbl <- base_ipea %>% # TABELA 1
  tbl_cross(row = sexo,
    col = dá.para.entender.que.um.homem.que.cresceu.em.uma.família.violenta.agrida.sua.mul,
    percent = "row")

tbl
```

Row {data-width=650, .tabset}
-----------------------------------------------------------------------

### **Se as mulheres soubessem se comportar haveriam menos estupros**

```{r}
library(ggplot2)
library(plotly)

renderPlotly({
  grafico2 <- filter(base_ipea, região.onde.foi.realizada.a.entrevista == input$Região) %>%
  ggplot(., aes(x = se.as.mulheres.soubessem.como.se.comportar..haveria.menos.estupros)) +
  geom_bar(fill = "#093c6d") +
  labs(x = " ", y = " ") +
  coord_flip() +
  theme_bw() +
  facet_grid(vars(), vars(sexo))

ggplotly(grafico2)
})

```

### **Tabela 2 (Resumo com todas regiões)**

```{r}
library(gtsummary)

tbl2 <- base_ipea %>% # TABELA 2
  tbl_cross(row = sexo,
    col = se.as.mulheres.soubessem.como.se.comportar..haveria.menos.estupros,
    percent = "row")

tbl2

```

Outras informações relevantes:
================================

columns {data-width=350}
-----------------------------------------------------------------------

### **Etinia**

```{r}

library(ggplot2)
library(plotly)

etinias <- 
  ggplot(base_ipea) +
  aes(x = cor.ou.raça) +
  geom_bar(fill = "#092e52") +
  labs(x = " ", y = "N° de Entrevistados") +
  theme_bw()

ggplotly(etinias)

```

### **Religião**

```{r}
library(ggplot2)
library(plotly)
library(forcats)

religiao <- base_ipea %>%
  mutate(religião = fct_lump(religião, 2, other_level = "Outros")) # Reclassificação do fator religião para níveis menos gerais

bar <- ggplot(religiao, aes(x = factor(1) , fill = factor(religião))) +
  geom_bar(width = 1) +
  labs(x = " ", y = "N° de Entrevistados") +
  theme_bw()

ggplotly(bar)

```

columns {data-width=350}
-------------------------------------------------------------
### **Idade** 
```{r}

library(ggplot2)
library(plotly)

idade <- ggplot(base_ipea) +
  aes(x = idade..qual.a.sua.idade..em.anos.completos..) +
  geom_histogram(bins = 30L, fill = "#052f58") +
  labs(x = " ", y = "N° de Entrevistados") +
  theme_bw()

ggplotly(idade)
```

