---
title: "Sera que a regiao contribui na formacao do preconceito sexista?"
output:
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    theme: cerulean
runtime: shiny
---

```{r setup, include=FALSE}
library(shiny)
library(tidyverse)
library(dplyr)
library(tidyr)
library(shiny)
library(flexdashboard)
library(magrittr)
library(plotly)
library(esquisse)
library(gtsummary)
base_ipea <- as_tibble(read.csv2("base_ipea.csv", stringsAsFactors = T)) # Lendo a base de dados
```

Analise por Regiao
=======

Inputs  {data-width=200 .sidebar}
----------
```{r}
selectInput("Regiao", label = "Regiao onde foi realizada a entrevista:", 
            choices = unique(base_ipea$regiao), selected = "SUDESTE")
```

**O absurdo é absurdo. Porém, depende!**

É curioso observar como o movimento das opiniões acontecem 
em função da região selecionada. Embora a maiorida dos 
entrevistados tendam a concordar, é possível observar um 
deslocamento na concordância de ambas afirmações.


Row {data-width=650, .tabset}
-----------------------------------------------------------------------

### Da pra entender que um homem que cresceu em uma familia violenta agrida sua mulher

```{r}
library(ggplot2)
library(plotly)
renderPlotly({
  grafico1 <- filter(base_ipea, regiao == input$Regiao) %>%
  ggplot(.,aes(x = da.pra.entender.que.um.homem.que.cresceu.em.uma.familia.violenta.agrida.sua.mulher, fill = sexo)) +
  geom_bar(position = "dodge") +
  #scale_fill_viridis_d(option = "cividis") +
  labs(x = " ", y = "N° de Entrevistados") +
  coord_flip() +
  theme_bw()
ggplotly(grafico1)
})
```

### Tabela 1 (Resumo com todas regioes)

```{r}
library(gtsummary)
tbl <- base_ipea %>% # TABELA 1
  tbl_cross(row = sexo,
    col = da.pra.entender.que.um.homem.que.cresceu.em.uma.familia.violenta.agrida.sua.mulher,
    percent = "row")
tbl
```

Row {data-width=650, .tabset}
-----------------------------------------------------------------------

### Se as mulheres soubessem se comportar haveriam menos estupros

```{r}
library(ggplot2)
library(plotly)
renderPlotly({
  grafico2 <- filter(base_ipea, regiao == input$Regiao) %>%
  ggplot(., aes(x = se.as.mulheres.soubessem.como.se.comportar..haveria.menos.estupros)) +
  geom_bar(fill = "#FF3900") +
  labs(x = " ", y = " ") +
  coord_flip() +
  theme_bw() +
  facet_grid(vars(), vars(sexo))
ggplotly(grafico2)
})
```

### Tabela 2 (Resumo com todas regioes)

```{r}
library(gtsummary)
tbl2 <- base_ipea %>% # TABELA 2
  tbl_cross(row = sexo,
    col = se.as.mulheres.soubessem.como.se.comportar..haveria.menos.estupros,
    percent = "row")
tbl2
```

Outras informacoes relevantes:
================================

**Representatividade?** A distribuição dos dados não é homogênea. A religião
católica, por exemplo, tem um número expressivo de representantes em relação à
outras religiões contempladas pela pesquisa. Assim como as raças indígena e 
amarelo possuem as porções menos expressivas entre as pessoas entrevistadas.

rows {data-width=700}
-----------------------------------------------------------------------

### **Etinias**

```{r}

etinias <- 
  ggplot(base_ipea, aes(x = cor.ou.raca, fill = regiao)) +
  geom_bar(position = "dodge") +
  #labs(x = " ", title = "Cor ou Raça") +
  #ggtitle("Número de entrevistados")+
  xlab(" ") +
  ylab("N° de entrevistados")+
  theme_bw()

ggplotly(etinias)

```

### **Religiao**

```{r}

base_ipea <- base_ipea %>%  mutate(religiao2 = fct_lump(religiao, 2, other_level = "Outros")) # Reclassificacao do fator religiao para niveis menos gerais


df_pizza_porcent <- prop.table(table(base_ipea$religiao2)) # Criando uma tabela com as frequencias relativas das religioes
df_pizza_porcent <- as.data.frame(df_pizza_porcent)


grafico_pizza_iterativo = plot_ly(df_pizza_porcent, # plotando grafico interativo com plot_ly
                                  labels = ~Var1, 
                                  values = ~Freq, 
                                  type = 'pie') #%>%
  #layout(title = 'Frequencia relativa da Classe Social (%)')

grafico_pizza_iterativo
```

columns {data-width=250}
-------------------------------------------------------------
### **Idade** 

```{r}

# Separando os quartis

minimo <- min(base_ipea$idade)

q1 <- quantile(base_ipea$idade, 0.25)

q2 <- quantile(base_ipea$idade,0.5)

q3 <- quantile(base_ipea$idade,0.75)

maximo <- max(base_ipea$idade)

# Criando uma nova coluna com as classes criadas

base_ipea$classes_idade= 
  cut(base_ipea$idade, breaks = c(minimo, q1, q2, q3, maximo),
      labels = c("16-28", "28-41", "41-56", "56-88"),
      include.lowest = T)

# plotando o grafico

grafico_hist <- ggplot(base_ipea,aes(x=classes_idade,fill= regiao)) + 
  geom_bar(position = "dodge")+
  #ggtitle("Grafico histograma da distribuicao do numero de entrevistados")+
  xlab("Frequencia das idades por quartis") +
  ylab("Frequencia simples") +
  theme_bw()

ggplotly(grafico_hist)

```